### ISSUE TITLE
Make this a built-in transformer?

### ISSUE THREAD

**Issue by MichaelDeBoey** [excalidraw/gatsby-embedder-excalidraw#2]
I'd love to have this one by default in the plugin. 👊

@trevorblades @j-f1 @lipis Would you mind creating a PR for this please? 🤔

**Comment by trevorblades** [comment]
I'd be happy to do this, but I just wanted you to be aware that this transformer includes `puppeteer` as a dependency. I noticed that the other transformers don't have any dependencies. Would this be an issue?

**Comment by MichaelDeBoey** [comment]
@trevorblades Hmmm that would be a bummer, since that's a large one...

Although we could add this to the README that `puppeteer` needs to be installed whenever they want to use the Excalidraw embeds, like we also need `gatsby-plugin-twitter` when using the Twitter transformer. 🤔

Would be better if @excalidraw was providing an `oembed` endpoint or iframe though 🧐

**Comment by trevorblades** [comment]
It is a large one, but on the other hand, it won't have an impact on the bundle size of the built Gatsby website, since `puppeteer` is only used during the build process. The only output from this transformer is an inline SVG.

Here's a PR for this change: https://github.com/MichaelDeBoey/gatsby-remark-embedder/pull/122 🎉

**Comment by trevorblades** [comment]
As I expressed in https://github.com/MichaelDeBoey/gatsby-remark-embedder/pull/122#issuecomment-633141901, I think it makes the most sense to keep this as a separate library for now. If a dependency-free solution (ie. an API endpoint or oEmbed) appears in the future, we can revisit this. For now, it sounds like this would not be possible due to the nature of Excalidraw's encryption model: https://github.com/MichaelDeBoey/gatsby-remark-embedder/pull/122#issuecomment-633165937
